### ISSUE TITLE
Can't await Future like on Material Dialog's showDialog() 

### ISSUE THREAD

**Issue by irjayjay** [mera-company/flutter-overlay-dialog#6]
Hi!

I'm trying to make our existing dialog display in front of overlays on the screen. So I'm trying this library.

In our current implementation we return a bool when the dialog is closed. This bool is true if the user tapped the yes button and false if no.

I can't seem to find a way to replicate this behaviour with this library. It doesn't seem to return a future or allow a callback to be bound to it.

Any ideas?

**Comment by Anartem** [comment]
Hi!

Callback for pressed button looks like the next.

    DialogHelper().show(
      context,
      DialogWidget.alert(
        style: DialogStyle.material,
        title: "Alert Dialog Example",
        content: "This is an example of overlay dialog. Do you like it?",
        actions: [
          DialogAction(
            title: "No",
            handler: () {
              DialogHelper().hide(context);
              onNoPressed();
            },
          ),
          DialogAction(
            title: "Yes",
            handler: () {
              DialogHelper().hide(context);
              onYesPressed();
            },
          ),
        ],
      )
    );

**Comment by irjayjay** [comment]
Oh, I forgot to add: I'm making a custom widget, so it's DialogWidget.custom(), but there are no callbacks for that.

**Comment by irjayjay** [comment]
Of course! And I could just implement my own Completer in order to return a Future<bool>.
It was a long day by the time I made that post, I guess I wasn't braining anymore.

Thank you for your help.

**Comment by Anartem** [comment]
Welcome :)
